export const PostActionTypes = {
    FETCHING_POST_START: 'FETCHING_POST_START',
    FETCHING_POST_SUCCESS: 'FETCHING_POST_SUCCESS',
    FETCHING_POST_FAILED: 'FETCHING_POST_FAILED',
    SEARCH_POST: 'SEARCH_POST'
};