export const UserActionTypes = {
    FETCHING_USER_START: 'FETCHING_USER_START',
    FETCHING_USER_SUCCESS: 'FETCHING_USER_SUCCESS',
    FETCHING_USER_FAILED: 'FETCHING_USER_FAILED',
    SEARCH_USER: 'SEARCH_USER'
};